### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by meleu** [meleu/Used2BeTXT#1]
- [ ] Make option to change which artwork tag is set as `<image>` so you can switch between Box Front, Cart, Titles, Action and 3D Boxarts types after the gamelists are already made.
- [x] Remove any line with only an URL in the description.

**Comment by Used2bRX** [comment]
- [ ] `Platform: Nintendo Entertainment System` and `Platform: Famicom Disk System` entries in the synopsis.txt files located in `/Media/nes/Synopsis/` folder will treat these entries as if they were NES and not FDS games and look for roms and all media in the `/nes/` folders instead. (This should not occur if the synopsis, media and roms are located in the `/Media/fds/` directory though).

- [ ] Make option to change which artwork tag is set as `<marquee>` so you can switch between Box Front, Cart, Titles, Action and 3D Boxarts types after the gamelists are already made. (Same as what I believe you already did for the `<image>` tag).  This way we can easily change what type of image displays for two image types after the `gamelist.xml` is created.

_I'm going to add "dummy" `*.jpg` files in the Marquee folder since I don't actually have any marquee images, unless you have a better solution for this.  I think right now the script just wouldn't create `<marquee>` tags at all, so this request wouldn't actually do anything unless the original run of the script created those lines in the `gamelist.xml`_

- [ ] Add the following fields to the `Full` option:

- Translation
- Release Year: 
- Translated By: 
- Hack Release Year: 
- Hacked By: 
- Original Title: 
- Alternate Title: 

_These aren't always used in every synopsis, so it should only create these in the entries that have them in the `synopsis.txt` file_

- [ ] Use the `Players:` field in the `synopsis.txt` files to create two tags in the `gamelist.xml`. The first would be our standard `<players>` tag that uses your code to only show the maximum amount of players in the game, but also a `<players-full>` tag that would show the text string that I put on that line. Personally I prefer the way that we've displayed that on the XBox and I'm hoping that if this is built on my end I might one day be able to get somebody here to add that possible tag to the setup here. I know it wouldn't be usable for anything right now. Maybe we could just throw that in the "full" option and leave it out when we don't use that.

- [ ] `gamelist.xml` to `synopsis.txt` reverse-order feature.

**Comment by meleu** [comment]
@Used2bRX I think I'll have some free time later today. Will try to work on some of the things you mentioned.

The "gamelist-to-synopsis" feature will be pretty easy to implement.

> - [ ] `Platform: Nintendo Entertainment System` and `Platform: Famicom Disk System` entries in the synopsis.txt files located in `/Media/nes/Synopsis/` folder will treat these entries as if they were NES and not FDS games and look for roms and all media in the `/nes/` folders instead. (This should not occur if the synopsis, media and roms are located in the `/Media/fds/` directory though).

Can you confirm if you still want exactly what you're describing above?
